-- ── Stock Vitrina ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS vitrina_products (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name          TEXT NOT NULL,
  price         NUMERIC(10,2) NOT NULL DEFAULT 0,
  quantity      INTEGER NOT NULL DEFAULT 0,
  image_filename TEXT NOT NULL DEFAULT '',
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE vitrina_products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth_all" ON vitrina_products FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Seed initial stock
INSERT INTO vitrina_products (name, price, quantity, image_filename) VALUES
('ACONDICIONADOR SEDAL PEQUEÑO', 3.00, 8, 'ACONDICIONADOR SEDAL PEQUEÑO CAN-8 PRE-3.jpeg'),
('AFEITADORA GILLETE', 10.00, 5, 'AFEITADORA GILLETE CAN-5 PRE- 10.jpeg'),
('AFEITADORA GILLETE COMFORT', 15.00, 1, 'AFEITADORA GILLETE COMFORT CAN-1 PRE- 15.jpeg'),
('AGUA', 10.00, 2, 'AGUA CAN-2 PRE-10.jpeg'),
('ANTITRANSPIRANTE DOVE', 28.00, 2, 'ANTITRANSPIRANTE DOVE CAN-2 PRE-28.jpeg'),
('ANTITRANSPIRANTE NIVEA MAN', 28.00, 1, 'ANTITRANSPIRANTE NIVEA MAN CAN-1 PRE-28.jpeg'),
('ANTITRANSPIRANTE REXONA ADORONO', 17.00, 1, 'ANTITRANSPIRANTE REXONA ADORONO CAN1 PRE-17.jpeg'),
('ANTITRANSPIRANTE REXONA', 45.00, 1, 'ANTITRANSPIRANTE REXONA CAN-1 PRE- 45.jpeg'),
('CEPILLO DENTAL DOCTOR DENT CHEAPER', 11.00, 2, 'CEPILLO DENTAL DOCTOR DENT CHEAPER CA-2 PRE-11.jpeg'),
('CEPILLO DENTAL DOCTOR DENT POPULAR', 12.00, 3, 'CEPILLO DENTAL DOCTOR DENT POPULAR CA-3 PRE-12.jpeg'),
('CEPILLO DENTAL DOCTOR DENT SUPERMAX', 8.00, 2, 'CEPILLO DENTAL DOCTOR DENT SUPERMAX CAN-2 PRE-8.jpeg'),
('CEPILLO DENTAL DOCTOR DENT SUPERTEX', 10.00, 4, 'CEPILLO DENTAL DOCTOR DENT SUPERTEX CAN-4 PRE-10.jpeg'),
('CEPILLO DENTAL MAIC', 12.00, 6, 'CEPILLO DENTAL MAIC CAN-6 PRE-12.jpeg'),
('CHOCOLATE DE DINOSAURIO', 11.00, 3, 'CHOCOLATE DE DINOSAURIO CAN-3 PRE-11.jpeg'),
('CHOCOLATE PEQUEÑO', 8.50, 2, 'CHOCOLATE PEQUEÑO CAN-2 PRE-8,50.jpeg'),
('DINOSAURIO', 160.00, 9, 'DINOSAURIO CAN-9 PRE-160.jpeg'),
('ECO TEA', 20.00, 4, 'ECO TEA CAN-4 PRE-20.jpeg'),
('GRAJEAS', 11.00, 5, 'GRAJEAS CAN-5 PRE-11.jpeg'),
('HILO DENTAL COLGATE', 38.00, 2, 'HILO DENTAL COLGATE CAN-2 PRE- 38.jpeg'),
('HILO DENTAL DOCTOR DENT', 18.00, 2, 'HILO DENTAL DOCTOR DENT CAN-2 PRE- 18.jpeg'),
('HISOPOS MAIC', 10.00, 2, 'HISOPOS MAIC CAN-2 PRE-10.jpeg'),
('HYDRAFOR', 14.00, 2, 'HYDRAFOR CAN-2 PRE-14.jpeg'),
('KLEENEX', 12.00, 4, 'KLEENEX CAN- 4 PRE- 12.jpeg'),
('NUTRIGOMAS', 7.00, 10, 'NUTRIGOMAS CAN-10 PRE-7.jpeg'),
('PROTECTOR LABIAL NIVEA ORIGINAL', 52.00, 1, 'PROTECTOR LABIAL NIVEA ORIGINAL CAN-1 PRE-52.jpeg'),
('PROTECTOR LABIAL SANACUTIS BIO', 20.00, 2, 'PROTECTOR LABIAL SANACUTIS BIO CAN-2 PRE-20.jpeg'),
('SAL DE HIDRATACION VITA DRIL', 24.00, 1, 'SAL DE HIDRATACION VITA DRIL CAN-1 PRE- 24.jpeg'),
('SUEROX', 18.00, 5, 'SUEROX CAN-5 PRE- 18.jpeg'),
('TABLETA DE CHOCOLATE BLANCO TABOADA 100g', 31.00, 4, 'TABLETA DE CHOCOLATE BLANCO TABOADA 100g CAN-4 PRE-31.jpeg'),
('TABLETA DE CHOCOLATE PEQUEÑO TE AMO', 11.00, 1, 'TABLETA DE CHOCOLATE PEQUEÑO TE AMO CAN-1 PRE-11.jpeg'),
('TABLETA DE CHOCOLATE TABOADA 100g', 31.00, 3, 'TABLETA DE CHOCOLATE TABOADA 100g CAN-3 PRE-31.jpeg'),
('TABLETA DE CHOCOLATE TABOADA PEQUEÑA', 11.00, 1, 'TABLETA DE CHOCOLATE TABOADA PEQUEÑA CAN-1 PRE-11.jpeg'),
('TOALLAS KOTEX NOCTURNA', 12.00, 2, 'TOALLAS KOTEX NOCTURNA CAN-2 PRE-12.jpeg'),
('TOALLAS KOTEX SPORT', 18.00, 2, 'TOALLAS KOTEX SPORT CAN-2 PRE- 18.jpeg'),
('TOALLAS NOSOTRAS NORMAL', 15.00, 3, 'TOALLAS NOSOTRAS NORMAL CAN-3 PRE-15.jpeg'),
('TOALLITAS HUMEDAS CARIÑOSITOS', 15.00, 2, 'TOALLITAS HUMEDAS CARIÑOSITOS CAN-2 PRE- 15.jpeg'),
('TOALLITAS HUMEDAS FERDY', 10.00, 3, 'TOALLITAS HUMEDAS FERDY CAN-3 PRE-10.jpeg'),
('TURRON CHOCOMANIES', 15.00, 1, 'TURRON CHOCOMANIES CAN-1 PRE-15.jpeg'),
('TURRON DE ALMENDRA', 15.00, 1, 'TURRON DE ALMENDRA CAN-1 PRE-15.jpeg'),
('TURRON DE COCO 40g', 8.00, 2, 'TURRON DE COCO 40g CAN-2 PRE-8.jpeg')
ON CONFLICT DO NOTHING;
